# Generated by Django 4.1.5 on 2023-01-16 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_category_options_designerproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='designerproduct',
            old_name='prodname',
            new_name='title',
        ),
    ]
