# Generated by Django 4.1.5 on 2023-01-18 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_rename_prodname_designerproduct_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='designerproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='upload/designerproduct_images'),
        ),
    ]
