# Generated by Django 4.1.5 on 2023-01-27 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_userprofile_address_userprofile_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='fullname',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
